source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'YouTubeFloatingPlayer_Example' do
  pod 'YouTubeFloatingPlayer', :path => '../'

  target 'YouTubeFloatingPlayer_Tests' do
    inherit! :search_paths
    
  end
end
